### PR TITLE
Support for Node.js 10, 12, and 13

### PR DESCRIPTION
**Pull request by gustavnikolaj**
We are trying to upgrade a few older apps which rely on this module, and we were unable to get it to compile on node versions newer than node 8.

I tried to make as small and focused commits as possible, but it got a bit out of hand when I tackled node 12.

The most recent version of nan drops support for node older than 8, so I removed them from CI as well. I updated mocha, as npm was warning about security issues (no changes in the API).

I hope that you can excuse the batching up of changes in this PR. Feel free to cherry-pick instead if that is easier to manage.

### CODE REVIEW

**Comment by wezm** [comment]
Wow thanks for this. It seems that the Travis CI is stopped working so I've re-added it. It seems there's no way for me to manually trigger a build against a remote branch so I pulled your changes and pushed them to a branch and that seems to have set it off.

**Comment by gustavnikolaj** [comment]
The CI run on travis was successful. Is there anything I can do to help move it forward now? :-)

**Comment by wezm** [comment]
> Is there anything I can do to help move it forward now?

I understand you're probably keen to get a new release with the changes. I'll merge now and aim to get a release out on the weekend.

**Comment by wezm** [comment]
Ok I published a release.

**Comment by gustavnikolaj** [comment]
Thanks alot @wezm. Just wanted to check in and let you know that we have shipped it to production and been running it for a while without any issues coming up.

**Comment by wezm** [comment]
Excellent, great to hear. Thanks again for the PR.

**Comment by gustavnikolaj** [comment]
@wezm I just noticed that it seems you forgot to push the tag for v2.0.0 to this repo. It's available on npmjs.com but not here on github :-)

**Comment by wezm** [comment]
Ahh good pick up. Now tagged.

**Pull request merged**
